name: flutter_bloc_architecture
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  bloc: ^8.1.4
  connectivity_plus: ^5.0.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  go_router: ^13.2.2
  http: ^1.2.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.6

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
